# NumPy

In [238]:
import numpy as np # Import Numpy

## Basic usage

In [239]:
list = [1, 2, 3, 4, 5, 6] # Normal Py list
arr = np.array(list) # Convert the list to Numpy array

In [240]:
matriz = [1,2,3], [4,5,6], [7,8,9] # Lists
matriz = np.array(matriz) # Convert the lists to Numpy array in 2D (matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Index & slices

In [241]:
arr[1::2] # Selecting values in the array
matriz[::-1, 1:2] # Selecting values in the 2D matriz
matriz[1,2] * matriz[0,2] # Operations with matriz values

18

## Data type

In [242]:
arr.dtype # Return the variable type 
arr = arr.astype(np.bool_) # Convert the variable type

## Dimentions

In [243]:
scalar = np.array(42) # 0 dimentions array = SCALAR
scalar.ndim

0

In [244]:
vector = np.array([1,2,3]) # 1 dimention array = VECTOR
vector.ndim

1

In [245]:
matriz = np.array([[1,2],[3,4]]) # 2 dimentions array = MATRIZ
matriz.ndim

2

In [246]:
tensor = np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]]) # 3 dimentions array = TENSOR
print(tensor, tensor.ndim) 

[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]] 3


## Operations with imentions arrays

In [247]:
vector = np.array([1,2,3], ndmin=10) # Minimum dimentions = 10
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [248]:
tensor_1 = np.expand_dims(tensor, axis=3) # Extend the tensor in the 3rd dimention
print(tensor_1, tensor_1.ndim)

[[[[1]
   [2]]

  [[3]
   [4]]

  [[5]
   [6]]]


 [[[1]
   [2]]

  [[3]
   [4]]

  [[5]
   [6]]]] 4


In [249]:
np.arange(0,10, 2) # Create an array with values from 0 to 10 with steps of 2

array([0, 2, 4, 6, 8])

In [250]:
np.zeros((10, 5)) # Create a 10x5 array with zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [251]:
np.linspace(0,10,20) # Create an array with 20 values from 0 to 10 

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [252]:
np.eye(5) # Create a 5x5 boolean matrix with the diagonal in true

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [253]:
np.random.randint(1,15,(10,5)) # Create a 10x5 array with random values between 1 and 15

array([[ 3,  7, 14, 13,  6],
       [11,  2,  6,  3,  7],
       [10, 13,  8, 12,  7],
       [ 5,  2, 10,  4,  2],
       [14, 11,  8,  7,  3],
       [ 5,  7,  6, 10,  6],
       [ 8,  8, 10,  1,  6],
       [ 6,  6,  2, 14,  1],
       [ 3,  9,  4, 10, 13],
       [ 7, 11, 10, 13, 14]])

## Shape & reshape

In [254]:
arr = np.random.randint(1,10,(3,2))
print(arr)
arr.shape # Return the shape of the array (X, Y, Z)

[[4 7]
 [8 7]
 [2 5]]


(3, 2)

In [255]:
arr.reshape(1,6) # Change the shape of the array (1X 6Y)

array([[4, 7, 8, 7, 2, 5]])

In [256]:
np.reshape(arr,(3,2),'C') # Return the reshape like the C language
np.reshape(arr,(3,2),'F') # Return the reshape like the Fortran language
np.reshape(arr,(2,3),'A') # Return the reshape like your PC optimized language


array([[4, 7, 8],
       [7, 2, 5]])

## NumPy principal functions

In [257]:
arr = np.random.randint(1,20,10) # Create a 10x1 array with random values between 1 and 20
arr

array([14,  5, 18, 11, 16, 14,  9,  7,  2, 13])

In [258]:
matriz = arr.reshape(2,5) # Change the shape of the array (2X 5Y)
matriz

array([[14,  5, 18, 11, 16],
       [14,  9,  7,  2, 13]])

In [259]:
matriz.max() # Return the maximum value of the array (the same with MIN)

18

In [260]:
matriz.max(1) # Return the maximum value of the array in each line (the same with MIN)

array([18, 14])

In [261]:
matriz.argmax(0) # Return the index of the maximum value of the array in each line (the same with MIN)

array([0, 1, 0, 0, 0])

In [262]:
matriz.ptp() # Return the difference between the minimum and the maximum value of the array (pit-to-pit)

16

In [263]:
np.percentile(arr,50) # Return the 50% percentile of the array

12.0

In [264]:
np.sort(arr) # Sort the array

array([ 2,  5,  7,  9, 11, 13, 14, 14, 16, 18])

In [265]:
np.median(arr) # The median of the array

12.0

In [266]:
np.median(matriz, 0) # The median of the matriz in 0 dimention

array([14. ,  7. , 12.5,  6.5, 14.5])

In [267]:
np.std(arr) # The standard deviation of the array

4.825971404805461

In [268]:
np.var(arr) # The variance of the array (standard deviation ** 2)

23.29

In [269]:
np.mean(arr) # The mean of the array

10.9

In [270]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6]) # This will trouble an error for the dimentions diff
d = np.concatenate((a,b.T), axis=0) # This will concatenate the array a with the transpose of b to fix the error
b = np.expand_dims(b,axis=0) # Expand the array in the 0 dimention to fix  the error
c = np.concatenate((a,b), axis=0) # Concat the arrays in the 0 dimention

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

### Copy

In [ ]:
arr = np.arange(0,11) 
new_arr = arr[0:6] # Slice the arr
new_arr[:] = 0 # Change the values of the slice to 0
arr # We can see that our new_arr change the old one
print(new_arr)
print(arr)

arr = np.arange(0,11) 
new_arr = arr.copy() # Copy the arr correctly
new_arr[:] = 1 # Change the values of the slice to 0
arr # We can see that our new_arr NO change the old one
print(new_arr)
print(arr)


[0 0 0 0 0 0]
[ 0  0  0  0  0  0  6  7  8  9 10]
[1 1 1 1 1 1 1 1 1 1 1]
[ 0  1  2  3  4  5  6  7  8  9 10]


### Conditions

In [ ]:
arr = np.linspace(1,10,10,dtype='int8')
arr

condition_arr = arr[(arr > 5) & (arr < 9)] # Return the values between 5 and 9
print(condition_arr)
print(arr)  

[6 7 8]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr[arr > 5] = 99 # Change the values of the array greater than 5 to 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

## Operations

In [ ]:
arr = np.arange(0,10)

print(arr * 2) # Multiply the array values by 2
print(arr + 2) # Add 2 to the array values

[ 0  2  4  6  8 10 12 14 16 18]
[ 2  3  4  5  6  7  8  9 10 11]


In [ ]:
arr2 = arr.copy() * 3

arr * arr2 # Multiply two arrays depending on the index

array([  0,   3,  12,  27,  48,  75, 108, 147, 192, 243])

In [ ]:
matriz = arr.reshape(2,5) # Reshape the arr and convert it to a matriz
matriz2 = matriz.copy() * 2
matriz + matriz2 # Add the matriz values depending on the index

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [ ]:
np.matmul(matriz, matriz2.T) # Return the dot product of the matrices (need the transpose)

array([[ 60, 160],
       [160, 510]])

In [ ]:
matriz = np.array([1,1,2,2,2,2,3,4,5,6,7,8,8,8,8,8])
unique = np.unique(matriz) # Return the arr without the repeated values
unique

array([1, 2, 3, 4, 5, 6, 7, 8])

# Pandas

## Series and dataframes

In [ ]:
import pandas as pd

In [ ]:
psg_players = pd.Series(['Navas', 'Mbappe', 'Neymar', 'Messi'],
          index=[1,7,10,30]
          ) # Create a Serie with the values and the index with Pandas
print(psg_players)

psg_players  = {1:'Navas', 7:'Mbappe', 10:'Neymar', 30:'Messi'} 
print(pd.Series(psg_players)) # Create a Serie with the values and the index with a python dict


1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object
1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object


1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [ ]:
dict = {'Jugador':['Luis Suárez','Jorge Molina', 'Antonio Puertas', 'Germán Sánchez', 'Luis Milla', 'Luís Manuel Arantes Maximiano'],
      'Posición':['Delantero', 'Delantero', 'Centrocampista', 'Defensa', 'Centrocampista', 'Portero'],
      'Altura':[185.0, 187.0, 185.0, 187.0, 175.0, 190.0],
      'Goles':[7, 7, 5, 2, 2, 0],
 }
df_Players = pd.DataFrame(dict) # Create a dataframe with a python dict
print(df_Players)

                         Jugador        Posición  Altura  Goles
0                    Luis Suárez       Delantero   185.0      7
1                   Jorge Molina       Delantero   187.0      7
2                Antonio Puertas  Centrocampista   185.0      5
3                 Germán Sánchez         Defensa   187.0      2
4                     Luis Milla  Centrocampista   175.0      2
5  Luís Manuel Arantes Maximiano         Portero   190.0      0


In [ ]:
df_Players.columns # Return the columns of the dataframe

Index(['Jugador', 'Posición', 'Altura', 'Goles'], dtype='object')

In [ ]:
df_Players.index # return the index of the dataframe

RangeIndex(start=0, stop=6, step=1)

In [ ]:
pd.DataFrame(dict, index = [9, 23, 10, 6, 5, 1]) # Create a dataframe with a python dict and the custom index

Jugador        Posición  Altura  Goles
9                     Luis Suárez       Delantero   185.0      7
23                   Jorge Molina       Delantero   187.0      7
10                Antonio Puertas  Centrocampista   185.0      5
6                  Germán Sánchez         Defensa   187.0      2
5                      Luis Milla  Centrocampista   175.0      2
1   Luís Manuel Arantes Maximiano         Portero   190.0      0

## File import

In [ ]:
original = pd.read_csv('./data/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv', sep=',', header=0) # Read a csv file and set the sep and header (there are others options)
original

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
caracters = pd.read_json('./data/hpcaractersdatadraw.json', typ = 'Series') # Read a json file and convert it to a pandas Series
caracters

0       {'Name': 'Mrs. Abbott', 'Link': 'https://www.h...
1       {'Name': 'Hannah Abbott', 'Link': 'https://www...
2       {'Name': 'Abel Treetops', 'Link': 'https://www...
3       {'Name': 'Euan Abercrombie', 'Link': 'https://...
4       {'Name': 'Aberforth Dumbledore', 'Link': 'http...
                              ...                        
1935    {'Name': 'Georgi Zdravko', 'Link': 'https://ww...
1936    {'Name': 'Zograf', 'Link': 'https://www.hp-lex...
1937    {'Name': 'Zonko', 'Link': 'https://www.hp-lexi...
1938    {'Name': 'Valentina Vázquez', 'Link': 'https:/...
1939    {'Name': 'Zygmunt Budge', 'Link': 'https://www...
Length: 1940, dtype: object

In [ ]:
df_books = original.copy()
df_books[0:4] # Return the first 4 rows of the dataframe

Name              Author  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7   
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   
3                   1984 (Signet Classics)       George Orwell          4.7   

   Reviews  Price  Year        Genre  
0    17350      8  2016  Non Fiction  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction  
3    21424      6  2017      Fiction

In [ ]:
df_books[['Name', 'Author', 'Genre']] # Return the columns Name, Author and Genre of the dataframe

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author        Genre  
0                    JJ Smith  Non Fiction  
1                Stephen King      Fiction  
2          Jordan B. Peterson  Non Fiction  
3               George Orwell      Fiction  
4    National Geographic Kids  Non Fiction  
..                        ...          ...  
545               Jeff Kinney      Fiction  
546               Jen Sincero  Non Fiction  
547               Jen Sincero  Non Fiction  
548               Jen Sincero  Non Fiction  
549               Jen Sincero  Non Fiction  

[550 rows x 3 columns]

### Loc and iloc filter

In [ ]:
df_books.loc[0:4, ['Name', 'Reviews']] * -1 # We can use the loc method to get the rows and columns we want and do operations

Name  Reviews
0        -17350
1         -2052
2        -18979
3        -21424
4         -7665

In [ ]:
df_books.loc[:,['Author']] == 'JJ Smith' # Filter and return booleans dates

Author
0      True
1     False
2     False
3     False
4     False
..      ...
545   False
546   False
547   False
548   False
549   False

[550 rows x 1 columns]

In [ ]:
print(df_books.iloc[:3] * -1) # Iloc is like loc but search by index

  Name Author  User Rating  Reviews  Price  Year Genre
0                     -4.7   -17350     -8 -2016      
1                     -4.6    -2052    -22 -2011      
2                     -4.7   -18979    -15 -2018      


## Add and drop things

### Drop columns 

In [ ]:
df_books.drop(['Genre', 'Name', 'Reviews'], axis=1).head(2) # Remove the columns Genre, Name and Reviews temporaly

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
df_books_copy2 = df_books.copy()
df_books_copy2.drop('Genre', axis=1, inplace=True) # Delete a column inplace (permanent)
df_books_copy2.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year  
0  2016  
1  2011

In [ ]:
df_books_copy3 = df_books.copy()
df_books_copy3 = df_books_copy3.drop('Genre', axis=1) # Another way to delete a column permanently
df_books_copy3.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year  
0  2016  
1  2011

### Drop rows

In [ ]:
df_books.drop([0,3,4], axis=0).head(5) # Delete the register 0, 3 and 4 temporaly

Name               Author  \
1                                  11/22/63: A Novel         Stephen King   
2            12 Rules for Life: An Antidote to Chaos   Jordan B. Peterson   
5      A Dance with Dragons (A Song of Ice and Fire)  George R. R. Martin   
6  A Game of Thrones / A Clash of Kings / A Storm...  George R. R. Martin   
7                     A Gentleman in Moscow: A Novel          Amor Towles   

   User Rating  Reviews  Price  Year        Genre  
1          4.6     2052     22  2011      Fiction  
2          4.7    18979     15  2018  Non Fiction  
5          4.4    12643     11  2011      Fiction  
6          4.7    19735     30  2014      Fiction  
7          4.7    19699     15  2017      Fiction

In [ ]:
df_books_copy = df_books.copy()
df_books_copy.drop([0,1,2], axis=0, inplace=True) # Delete the register 0, 1 and 2 inplace (permanent)
df_books_copy.head(2)

Name  \
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

### Add columns

In [ ]:
df_books['New_column'] = np.nan  # Create a NaN column in the dataframe
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  New_column  
0  2016  Non Fiction         NaN  
1  2011      Fiction         NaN

In [ ]:
data = np.arange(0, df_books.shape[0]) + 1 # Save the data (ids + 1) in a array
df_books['Range'] = data # Create a column with the data saved
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     New_column  Range  
0           NaN      1  
1           NaN      2  
2           NaN      3  
3           NaN      4  
4           NaN      5  
..          ...    ...  
545         NaN    546  
546         NaN    547  
547         NaN    548  
548         NaN    549  
549         NaN    550  

[550 rows x 9 columns]

### Add rows

In [ ]:
df_books.append(df_books) # Append the dataframe to itself (duplicate the dataframe)

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     New_column  Range  
0           NaN      1  
1           NaN      2  
2           NaN      3  
3           NaN      4  
4           NaN      5  
..          ...    ...  
545         NaN    546  
546         NaN    547  
547         NaN    548  
548         NaN    549  
549         NaN    550  

[1100 rows x 9 columns]

## Null data management

In [ ]:
dict = {'Col1': [1,2,3,np.nan],
 'Col2': [4,np.nan,6,7],
 'Col3': ['a','b','c',None],
 }

df = pd.DataFrame(dict) # Create a dataframe with a python dict (with nulls values)
df

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

In [ ]:
df.isnull()*1 # If the value is null return 1, else return 0

Col1  Col2  Col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

In [ ]:
df.fillna('Missing') # Replaze the null values with the string 'Missing'

Col1     Col2     Col3
0      1.0      4.0        a
1      2.0  Missing        b
2      3.0      6.0        c
3  Missing      7.0  Missing

In [ ]:
df.fillna(df.mean()) # Replaze the null values with the mean of the column

/tmp/ipykernel_106451/1535641118.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.mean()) # Replaze the null values with the mean of the column


Col1      Col2  Col3
0   1.0  4.000000     a
1   2.0  5.666667     b
2   3.0  6.000000     c
3   2.0  7.000000  None

In [ ]:
df.interpolate() # Try to interpolate the null values (math)

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   3.0   7.0  None

In [ ]:
df.dropna() # Delete the rows with nulls values

Col1  Col2 Col3
0   1.0   4.0    a
2   3.0   6.0    c

## Conditional filters

In [274]:
mayor_a2016 = df_books ['Year'] > 2016 # Basic filter returning a boolean array
solo_de_ficcion = df_books['Genre'] == 'Fiction' # String filter returning a boolean array
print(mayor_a2016)
print(solo_de_ficcion)

0      False
1      False
2       True
3       True
4       True
       ...  
545     True
546    False
547     True
548     True
549     True
Name: Year, Length: 550, dtype: bool
0      False
1       True
2      False
3       True
4      False
       ...  
545     True
546    False
547    False
548    False
549    False
Name: Genre, Length: 550, dtype: bool


In [275]:
df_books[mayor_a2016 & -solo_de_ficcion]  # Return the rows that are true in both boolean arrays (and descendent by the solo_de_ficcion array)

Name  \
2              12 Rules for Life: An Antidote to Chaos   
4    5,000 Awesome Facts (About Everything!) (Natio...   
8        A Higher Loyalty: Truth, Lies, and Leadership   
26                  Astrophysics for People in a Hurry   
32                                            Becoming   
..                                                 ...   
526                                      What Happened   
536  Whose Boat Is This Boat?: Comments That Don't ...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                               Author  User Rating  Reviews  Price  Year  \
2                  Jordan B. Peterson          4.7    18979     15  2018   
4            National Geographic Kids          4.8     7665     12  2019   
8                         James Comey          4.7     5983      3  2018   
26                Neil deGrasse Tyson          4.7     9374      9  2017   
32                     Michelle Obama          4.8    61133     11  2018   
..                                ...          ...      ...    ...   ...   
526            Hillary Rodham Clinton          4.6     5492     18  2017   
536  The Staff of The Late Show with
          4.6     6669     12  2018   
547                       Jen Sincero          4.7    14331      8  2017   
548                       Jen Sincero          4.7    14331      8  2018   
549                       Jen Sincero          4.7    14331      8  2019   

           Genre  New_column  Range  
2    Non Fiction         NaN      3  
4    Non Fiction         NaN      5  
8    Non Fiction         NaN      9  
26   Non Fiction         NaN     27  
32   Non Fiction         NaN     33  
..           ...         ...    ...  
526  Non Fiction         NaN    527  
536  Non Fiction         NaN    537  
547  Non Fiction         NaN    548  
548  Non Fiction         NaN    549  
549  Non Fiction         NaN    550  

[85 rows x 9 columns]

## Principal functions

In [ ]:
df_books.info() # Return the important information of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   NAME           550 non-null    object 
 1   AUTHOR         550 non-null    object 
 2   U.R            550 non-null    float64
 3   Reviews        550 non-null    int64  
 4   Price          550 non-null    int64  
 5   Year           550 non-null    int64  
 6   Genre          550 non-null    object 
 7   Nueva_Columna  0 non-null      float64
 8   Rango          550 non-null    int64  
dtypes: float64(2), int64(4), object(3)
memory usage: 38.8+ KB


In [ ]:
df_books.describe() # Return the basic statistics of the dataframe

U.R       Reviews       Price         Year  Nueva_Columna  \
count  550.000000    550.000000  550.000000   550.000000            0.0   
mean     4.618364  11953.281818   13.100000  2014.000000            NaN   
std      0.226980  11731.132017   10.842262     3.165156            NaN   
min      3.300000     37.000000    0.000000  2009.000000            NaN   
25%      4.500000   4058.000000    7.000000  2011.000000            NaN   
50%      4.700000   8580.000000   11.000000  2014.000000            NaN   
75%      4.800000  17253.250000   16.000000  2017.000000            NaN   
max      4.900000  87841.000000  105.000000  2019.000000            NaN   

            Rango  
count  550.000000  
mean   274.500000  
std    158.915596  
min      0.000000  
25%    137.250000  
50%    274.500000  
75%    411.750000  
max    549.000000

In [277]:
df_books.tail(2) # Return the last 2 rows of the dataframe
df_books.head(2) # Nos trae los N primeros registros (al contrario que .tail)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  New_column  Range  
0  2016  Non Fiction         NaN      1  
1  2011      Fiction         NaN      2

In [280]:
df_books.memory_usage(deep=True) # Return the memory usage of the dataframe

Index            128
Name           59737
Author         39078
User Rating     4400
Reviews         4400
Price           4400
Year            4400
Genre          36440
New_column      4400
Range           4400
dtype: int64

In [281]:
df_books['Author'].value_counts() # Return the count of the unique values of the column Author

Jeff Kinney                           12
Gary Chapman                          11
Rick Riordan                          11
Suzanne Collins                       11
American Psychological Association    10
                                      ..
Keith Richards                         1
Chris Cleave                           1
Alice Schertle                         1
Celeste Ng                             1
Adam Gasiewski                         1
Name: Author, Length: 248, dtype: int64

In [282]:
df_books.drop_duplicates() # Delete the duplicates of the dataframe keeping the first one

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     New_column  Range  
0           NaN      1  
1           NaN      2  
2           NaN      3  
3           NaN      4  
4           NaN      5  
..          ...    ...  
545         NaN    546  
546         NaN    547  
547         NaN    548  
548         NaN    549  
549         NaN    550  

[550 rows x 9 columns]

In [ ]:
df_books.drop_duplicates(keep='last') # Delete the duplicates of the dataframe but keep the last one

NAME  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       AUTHOR  U.R  Reviews  Price  Year        Genre  \
0                    JJ Smith  4.7    17350      8  2016  Non Fiction   
1                Stephen King  4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson  4.7    18979     15  2018  Non Fiction   
3               George Orwell  4.7    21424      6  2017      Fiction   
4    National Geographic Kids  4.8     7665     12  2019  Non Fiction   
..                        ...  ...      ...    ...   ...          ...   
545               Jeff Kinney  4.9     9413      8  2019      Fiction   
546               Jen Sincero  4.7    14331      8  2016  Non Fiction   
547               Jen Sincero  4.7    14331      8  2017  Non Fiction   
548               Jen Sincero  4.7    14331      8  2018  Non Fiction   
549               Jen Sincero  4.7    14331      8  2019  Non Fiction   

     Nueva_Columna  Rango  
0              NaN      0  
1              NaN      1  
2              NaN      2  
3              NaN      3  
4              NaN      4  
..             ...    ...  
545            NaN    545  
546            NaN    546  
547            NaN    547  
548            NaN    548  
549            NaN    549  

[550 rows x 9 columns]

In [ ]:
df_books.sort_values('Year', ascending = False) # Return the dataframe sorted by the column Year in descending order

NAME                 AUTHOR  \
549  You Are a Badass: How to Stop Doubting Your Gr...            Jen Sincero   
294  School Zone - Big Preschool Workbook - Ages 4 ...            School Zone   
489                   The Wonderful Things You Will Be  Emily Winfield Martin   
263    P is for Potty! (Sesame Street) (Lift-the-Flap)        Naomi Kleinberg   
130  Girl, Wash Your Face: Stop Believing the Lies ...          Rachel Hollis   
..                                                 ...                    ...   
418  The Last Olympian (Percy Jackson and the Olymp...           Rick Riordan   
38           Breaking Dawn (The Twilight Saga, Book 4)        Stephenie Meyer   
92   Eat This, Not That! Thousands of Simple Food S...        David Zinczenko   
139  Good to Great: Why Some Companies Make the Lea...            Jim Collins   
299                                  Sookie Stackhouse       Charlaine Harris   

     U.R  Reviews  Price  Year        Genre  Nueva_Columna  Rango  
549  4.7    14331      8  2019  Non Fiction            NaN    549  
294  4.8    23047      6  2019  Non Fiction            NaN    294  
489  4.9     8842     10  2019      Fiction            NaN    489  
263  4.7    10820      5  2019  Non Fiction            NaN    263  
130  4.6    22288     12  2019  Non Fiction            NaN    130  
..   ...      ...    ...   ...          ...            ...    ...  
418  4.8     4628      7  2009      Fiction            NaN    418  
38   4.6     9769     13  2009      Fiction            NaN     38  
92   4.3      956     14  2009  Non Fiction            NaN     92  
139  4.5     3457     14  2009  Non Fiction            NaN    139  
299  4.7      973     25  2009      Fiction            NaN    299  

[550 rows x 9 columns]

## Group by (like SQL)

In [285]:
df_books.groupby('Author').count() # Return the count of the unique values of the column Author

Name  User Rating  Reviews  Price  Year  Genre  \
Author                                                                       
Abraham Verghese               2            2        2      2     2      2   
Adam Gasiewski                 1            1        1      1     1      1   
Adam Mansbach                  1            1        1      1     1      1   
Adir Levy                      1            1        1      1     1      1   
Admiral William H. McRaven     1            1        1      1     1      1   
...                          ...          ...      ...    ...   ...    ...   
Walter Isaacson                3            3        3      3     3      3   
William Davis                  2            2        2      2     2      2   
William P. Young               2            2        2      2     2      2   
Wizards RPG Team               3            3        3      3     3      3   
Zhi Gang Sha                   2            2        2      2     2      2   

                            New_column  Range  
Author                                         
Abraham Verghese                     0      2  
Adam Gasiewski                       0      1  
Adam Mansbach                        0      1  
Adir Levy                            0      1  
Admiral William H. McRaven           0      1  
...                                ...    ...  
Walter Isaacson                      0      3  
William Davis                        0      2  
William P. Young                     0      2  
Wizards RPG Team                     0      3  
Zhi Gang Sha                         0      2  

[248 rows x 8 columns]

In [286]:
df_books.groupby('Author').count().loc['William Davis'] # Return the unique values when the Author is William Davis like an index

Name           2
User Rating    2
Reviews        2
Price          2
Year           2
Genre          2
New_column     0
Range          2
Name: William Davis, dtype: int64

In [288]:
df_books.groupby('Author').count().reset_index() # Reset index

Author  Name  User Rating  Reviews  Price  Year  \
0              Abraham Verghese     2            2        2      2     2   
1                Adam Gasiewski     1            1        1      1     1   
2                 Adam Mansbach     1            1        1      1     1   
3                     Adir Levy     1            1        1      1     1   
4    Admiral William H. McRaven     1            1        1      1     1   
..                          ...   ...          ...      ...    ...   ...   
243             Walter Isaacson     3            3        3      3     3   
244               William Davis     2            2        2      2     2   
245            William P. Young     2            2        2      2     2   
246            Wizards RPG Team     3            3        3      3     3   
247                Zhi Gang Sha     2            2        2      2     2   

     Genre  New_column  Range  
0        2           0      2  
1        1           0      1  
2        1           0      1  
3        1           0      1  
4        1           0      1  
..     ...         ...    ...  
243      3           0      3  
244      2           0      2  
245      2           0      2  
246      3           0      3  
247      2           0      2  

[248 rows x 9 columns]

In [289]:
df_books.groupby('Author').agg(['min','max']) # Return the min and max of all columns of the unique values of the column Author

Name  \
                                                                          min   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                             Leonardo da Vinci   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Divine Soul Mind Body Healing and Transmission...   

                                                                               \
                                                                          max   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                                    Steve Jobs   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Soul Healing Miracles: Ancient and New Sacred ...   

                           User Rating      Reviews        Price      Year  \
                                   min  max     min    max   min max   min   
Author                                                                       
Abraham Verghese                   4.6  4.6    4866   4866    11  11  2010   
Adam Gasiewski                     4.4  4.4    3113   3113     6   6  2017   
Adam Mansbach                      4.8  4.8    9568   9568     9   9  2011   
Adir Levy                          4.8  4.8    8170   8170    13  13  2019   
Admiral William H. McRaven         4.7  4.7   10199  10199    11  11  2017   
...                                ...  ...     ...    ...   ...  ..   ...   
Walter Isaacson                    4.5  4.6    3014   7827    20  21  2011   
William Davis                      4.4  4.4    7497   7497     6   6  2012   
William P. Young                   4.6  4.6   19720  19720     8   8  2009   
Wizards RPG Team                   4.8  4.8   16990  16990    27  27  2017   
Zhi Gang Sha                       4.6  4.6      37    220     6  17  2009   

                                        Genre              New_column      \
                             max          min          max        min max   
Author                                                                      
Abraham Verghese            2011      Fiction      Fiction        NaN NaN   
Adam Gasiewski              2017  Non Fiction  Non Fiction        NaN NaN   
Adam Mansbach               2011      Fiction      Fiction        NaN NaN   
Adir Levy                   2019      Fiction      Fiction        NaN NaN   
Admiral William H. McRaven  2017  Non Fiction  Non Fiction        NaN NaN   
...                          ...          ...          ...        ...  ..   
Walter Isaacson  

In [ ]:
df_books.groupby('AUthor').agg({'Reviews':['min','max'], 'Price':'sum'}) # Return data grouped by Author with own selected criterion

Reviews        Price
                               min    max   sum
AUTHOR                                         
Abraham Verghese              4866   4866    22
Adam Gasiewski                3113   3113     6
Adam Mansbach                 9568   9568     9
Adir Levy                     8170   8170    13
Admiral William H. McRaven   10199  10199    11
...                            ...    ...   ...
Walter Isaacson               3014   7827    61
William Davis                 7497   7497    12
William P. Young             19720  19720    16
Wizards RPG Team             16990  16990    81
Zhi Gang Sha                    37    220    23

[248 rows x 3 columns]

## Merge and concat

In [290]:
 # Create two dataframes
df1 = pd.DataFrame({
    'A':['A0', 'A1','A2','A3'],
    'B':['B0', 'B1','B2','B3'],
    'C':['C0', 'C1','C2','C3'],
    'D':['D0', 'D1','D2','D3'],
    })

df2 = pd.DataFrame({
    'A':['A5', 'A6','A7','A8'],
    'B':['B5', 'B6','B7','B8'],
    'C':['C5', 'C6','C7','C8'],
    'D':['D5', 'D6','D7','D8'],
    }) 

pd.concat([df1, df2], ignore_index= True) # Concatenate the dataframes (ignoring the index) by the X axis

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A5  B5  C5  D5
5  A6  B6  C6  D6
6  A7  B7  C7  D7
7  A8  B8  C8  D8

In [ ]:
pd.concat([df1, df2], axis=1, ignore_index= True) # Concatenate the dataframes (ignoring the index) by the Y axis

0   1   2   3   4   5   6   7
0  A0  B0  C0  D0  A5  B5  C5  D5
1  A1  B1  C1  D1  A6  B6  C6  D6
2  A2  B2  C2  D2  A7  B7  C7  D7
3  A3  B3  C3  D3  A8  B8  C8  D8

In [ ]:
izq = pd.DataFrame({'key':['k0','k1','k2','k3',],
 'A':['A5', 'A6','A7','A8'],
 'B':['B5', 'B6','B7','B8'],})

der = pd.DataFrame({'key':['k0','k1','k2','k3',],
 'C':['C5', 'C6','C7','C8'],
 'D':['D5', 'D6','D7','D8'],})

izq.merge(der, on='key') # Make a join between the dataframes (left to right for default)

key   A   B   C   D
0  k0  A5  B5  C5  D5
1  k1  A6  B6  C6  D6
2  k2  A7  B7  C7  D7
3  k3  A8  B8  C8  D8

In [295]:
izq = pd.DataFrame({'key':['k0','k1','k2','k3',],
 'A':['A5', 'A6','A7','A8'],
 'B':['B5', 'B6','B7','B8'],})

der = pd.DataFrame({'key_2':['k0','k1','k2','k3',],
 'C':['C5', 'C6','C7','C8'],
 'D':['D5', 'D6','D7','D8'],})

# izq.merge(der) # It will throw an error because the dataframes don't have the same columns
izq.merge(der, left_on='key', right_on='key_2') # Make a join between the dataframes but choosing the ON for no errors

key   A   B key_2   C   D
0  k0  A5  B5    k0  C5  D5
1  k1  A6  B6    k1  C6  D6
2  k2  A7  B7    k2  C7  D7
3  k3  A8  B8    k3  C8  D8

In [296]:
izq = pd.DataFrame({'key':['k0','k1','k2','k3',],
 'A':['A5', 'A6','A7','A8'],
 'B':['B5', 'B6','B7','B8'],})

der = pd.DataFrame({'key_2':['k0','k1','k2',np.nan,],
 'C':['C5', 'C6','C7','C8'],
 'D':['D5', 'D6','D7','D8'],})

izq.merge(der, left_on='key', right_on='key_2') # Make a join but without the NaN row in both dataframes

key   A   B key_2   C   D
0  k0  A5  B5    k0  C5  D5
1  k1  A6  B6    k1  C6  D6
2  k2  A7  B7    k2  C7  D7

In [297]:
izq = pd.DataFrame({'key':['k0','k1','k2','k3',],
 'A':['A5', 'A6','A7','A8'],
 'B':['B5', 'B6','B7','B8'],})

der = pd.DataFrame({'key_2':['k0','k1','k2',np.nan,],
 'C':['C5', 'C6','C7','C8'],
 'D':['D5', 'D6','D7','D8'],})

izq.merge(der, left_on='key', right_on='key_2', how='left') # Make a join but with the NaN row in both dataframes

key   A   B key_2    C    D
0  k0  A5  B5    k0   C5   D5
1  k1  A6  B6    k1   C6   D6
2  k2  A7  B7    k2   C7   D7
3  k3  A8  B8   NaN  NaN  NaN

## Join (index match)

In [298]:
df1 = pd.DataFrame({
    'B':['B0','B1','B2',],
    'A':['A5', 'A6','A7']},
    index=['k0','k1','k2',])

df2 = pd.DataFrame({
    'C':['C0','C1','C2',],
    'D':['D0', 'D1','D2']},
    index=['k0','k2','k3',])

df1.join(df2) # Make a join respecting the index of the dataframes

B   A    C    D
k0  B0  A5   C0   D0
k1  B1  A6  NaN  NaN
k2  B2  A7   C1   D1

In [299]:
df1 = pd.DataFrame({
    'B':['B0','B1','B2',],
    'A':['A5', 'A6','A7']},
    index=['k0','k1','k2',])

df2 = pd.DataFrame({
    'C':['C0','C1','C2',],
    'D':['D0', 'D1','D2']},
    index=['k0','k2','k3',])

df1.join(df2, how='inner') # Make an inner join

B   A   C   D
k0  B0  A5  C0  D0
k2  B2  A7  C1  D1

## Pivot table

In [302]:
df_books.pivot_table(index='Genre',columns='Year', values='Price',aggfunc='sum') # Return a table using the Genre like rows, unique years like columns and the sum of the price like values
# like a dinamic table

Year         2009  2010  2011  2012  2013  2014  2015  2016  2017  2018  2019
Genre                                                                        
Fiction       374   194   244   258   257   295   159   240   212   184   187
Non Fiction   396   480   511   507   473   437   362   419   357   342   317

## Melt

In [303]:
original.melt(id_vars='Year',value_vars='Genre').head(5) # Return a table using the Years like rows, the most common Genres like values and the row type like another value

Year variable        value
0  2016    Genre  Non Fiction
1  2011    Genre      Fiction
2  2018    Genre  Non Fiction
3  2017    Genre      Fiction
4  2019    Genre  Non Fiction

## Apply

In [ ]:
# For apply a function to a column
def two_times(value):
  return value * 2

original['Rating_2'] = original['User Rating'].apply(two_times) # Apply the function two_times to the column User Rating and save it in the new column Rating_2
original[['Rating_2', 'User Rating']]

Rating_2  User Rating
0         9.4          4.7
1         9.2          4.6
2         9.4          4.7
3         9.4          4.7
4         9.6          4.8
..        ...          ...
545       9.8          4.9
546       9.4          4.7
547       9.4          4.7
548       9.4          4.7
549       9.4          4.7

[550 rows x 2 columns]

In [304]:
original['Rating_2'] = original['User Rating'].apply(lambda x : x * 3) # Apply a lambda function for the column
original[['Rating_2', 'User Rating']]

Rating_2  User Rating
0        14.1          4.7
1        13.8          4.6
2        14.1          4.7
3        14.1          4.7
4        14.4          4.8
..        ...          ...
545      14.7          4.9
546      14.1          4.7
547      14.1          4.7
548      14.1          4.7
549      14.1          4.7

[550 rows x 2 columns]

In [305]:
original['Rating_2'] = original.apply(lambda x : x['User Rating'] * 2 if x['Genre'] == 'Fiction' else x['User Rating'], axis = 1)
original[['Rating_2', 'User Rating']] 

Rating_2  User Rating
0         4.7          4.7
1         9.2          4.6
2         4.7          4.7
3         9.4          4.7
4         4.8          4.8
..        ...          ...
545       9.8          4.9
546       4.7          4.7
547       4.7          4.7
548       4.7          4.7
549       4.7          4.7

[550 rows x 2 columns]